<a href="https://colab.research.google.com/github/JamesJang26/SNU-MEDINFO-study/blob/main/BERT_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install -U pandas

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.2/12.2 MB 46.9 MB/s eta 0:00:00
  Attempting uninstall: pandas
    Found existing installation: pandas 1.3.5
    Uninstalling pandas-1.3.5:
      Successfully uninstalled pandas-1.3.5


In [2]:
import pandas as pd

data_url = "https://raw.githubusercontent.com/socd06/medical-nlp/master/data/X.csv"
df = pd.read_csv(data_url)

In [3]:
df.head()

label  ...                                               text
0      4  ...  SUBJECTIVE:,  This 23-year-old white female pr...
1      4  ...  PAST MEDICAL HISTORY:, He has difficulty climb...
2      4  ...  HISTORY OF PRESENT ILLNESS: , I have seen ABC ...
3      3  ...  2-D M-MODE: , ,1.  Left atrial enlargement wit...
4      3  ...  1.  The left ventricular cavity size and wall ...

[5 rows x 3 columns]

In [4]:
df['label'].value_counts()

1    1640
2    1228
3    1149
4     982
Name: label, dtype: int64

In [5]:
df12 = df[df['label'].isin((1,2))]
df12

label  ...                                               text
18        1  ...  PROCEDURE: , Elective male sterilization via b...
20        1  ...  INDICATION:,  Prostate Cancer.,TECHNIQUE:,  3....
22        1  ...  DESCRIPTION:,  The patient was placed in the s...
23        1  ...  PREOPERATIVE DIAGNOSIS: , Voluntary sterility....
24        1  ...                               CHIEF COMPLAINT:,nan
...     ...  ...                                                ...
4592      2  ...  REASON FOR CONSULTATION:  ,Abnormal echocardio...
4593      2  ...  REASON FOR REFERRAL:,  The patient was referre...
4594      2  ...  CHIEF COMPLAINT: , Chest pain.,HISTORY OF PRES...
4595      2  ...  CHIEF COMPLAINT:,  A 5-month-old boy with coug...
4602      2  ...  CHIEF COMPLAINT:,  Abdominal pain.,HISTORY OF ...

[2868 rows x 3 columns]

In [6]:
df10 = df12.copy()
df10.loc[df10['label']==2, 'label'] = 0
df10

label  ...                                               text
18        1  ...  PROCEDURE: , Elective male sterilization via b...
20        1  ...  INDICATION:,  Prostate Cancer.,TECHNIQUE:,  3....
22        1  ...  DESCRIPTION:,  The patient was placed in the s...
23        1  ...  PREOPERATIVE DIAGNOSIS: , Voluntary sterility....
24        1  ...                               CHIEF COMPLAINT:,nan
...     ...  ...                                                ...
4592      0  ...  REASON FOR CONSULTATION:  ,Abnormal echocardio...
4593      0  ...  REASON FOR REFERRAL:,  The patient was referre...
4594      0  ...  CHIEF COMPLAINT: , Chest pain.,HISTORY OF PRES...
4595      0  ...  CHIEF COMPLAINT:,  A 5-month-old boy with coug...
4602      0  ...  CHIEF COMPLAINT:,  Abdominal pain.,HISTORY OF ...

[2868 rows x 3 columns]

In [7]:
df10_shuffled = df10.sample(frac=1, random_state=0)
df10_shuffled

label  ...                                               text
3832      0  ...  HISTORY OF PRESENT ILLNESS:,  The patient is a...
551       1  ...  PREOPERATIVE DIAGNOSIS:  ,Metastatic renal cel...
4370      0  ...  CHIEF COMPLAINT: , Anxiety, alcohol abuse, and...
4299      0  ...  CHIEF COMPLAINT: , Both pancreatic and left ad...
556       1  ...  PREOPERATIVE DIAGNOSIS: , Soft tissue mass, ri...
...     ...  ...                                                ...
783       1  ...  PREPROCEDURE DIAGNOSIS:,  Foreign body of the ...
855       1  ...  PROCEDURE:,  Upper endoscopy with biopsy.,PROC...
1712      0  ...  CT ABDOMEN WITHOUT CONTRAST AND CT PELVIS WITH...
4336      0  ...  CC: ,Depressed mental status.,HX: ,29y/o femal...
4461      0  ...  SUBJECTIVE:,  The patient's assistant brings i...

[2868 rows x 3 columns]

In [10]:
!pip install -U datasets transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [12]:
from datasets import Dataset

dataset = Dataset.from_pandas(df10_shuffled, preserve_index = True)

dataset = dataset.train_test_split(test_size = 0.1, seed = 0)

dataset

DatasetDict({
    train: Dataset({
        features: ['label', 'description', 'text', '__index_level_0__'],
        num_rows: 2581
    })
    test: Dataset({
        features: ['label', 'description', 'text', '__index_level_0__'],
        num_rows: 287
    })
})

In [13]:
from pprint import pprint
pprint(dataset['test'][42])

{'__index_level_0__': 159,
 'description': ' Circumcision - 7 ',
 'label': 1,
 'text': 'PROCEDURE:,  Circumcision.,ANESTHESIA: , EMLA.,FINDINGS: , Normal '
         'penis.  The foreskin was normal in appearance and measured 1.6 cm.  '
         'There was no bleeding at the circumcision site.,PROCEDURE:,  Patient '
         'was placed on the circumcision restraint board.  EMLA had been '
         'applied approximately 90 minutes before.  A time-out was completed '
         'satisfactorily per protocol.  The area was prepped with Betadine.  '
         'The foreskin was grasped with sterile clamps and was dissected away '
         'from the corona and the glans penis with blunt dissection.  A Mogen '
         'clamp was applied to the cervix.  The excess foreskin was excised '
         'with the scalpel.  The clamp was removed.  At this point, the '
         'procedure was terminated.  Sterile Vaseline and gauze was applied to '
         'the glans penis.  There were no complications. 

In [15]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification

#BERT-BASE
model_path = "bert-base-uncased"

#BERT 토크나이저 가져오기
tokenizer = AutoTokenizer.from_pretrained(model_path)

#BERT 모델 가져오기
model = AutoModelForSequenceClassification.from_pretrained(model_path)

Downloading:   0%|          | 0.00/28.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/570 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/232k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/466k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/440M [00:00<?, ?B/s]

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForSequenceClassification: ['cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.bias', 'cls.predictions.decoder.weight', 'cls.seq_relationship.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at

In [16]:
def tokenize_many(examples):
  return tokenizer(
      examples['text'],
      max_length = model.config.max_position_embeddings,
      padding = 'max_length',
      truncation = True
  )

In [17]:
dataset = dataset.map(tokenize_many, batched = True)

  0%|          | 0/3 [00:00<?, ?ba/s]

  0%|          | 0/1 [00:00<?, ?ba/s]

In [18]:
print(dataset['test'][42].keys())

dict_keys(['label', 'description', 'text', '__index_level_0__', 'input_ids', 'token_type_ids', 'attention_mask'])


In [19]:
print(dataset['test'][42]['input_ids'])

[101, 7709, 1024, 1010, 25022, 11890, 2819, 28472, 1012, 1010, 2019, 25344, 1024, 1010, 7861, 2721, 1012, 1010, 9556, 1024, 1010, 3671, 19085, 1012, 1996, 18921, 29334, 2001, 3671, 1999, 3311, 1998, 7594, 1015, 1012, 1020, 4642, 1012, 2045, 2001, 2053, 9524, 2012, 1996, 25022, 11890, 2819, 28472, 2609, 1012, 1010, 7709, 1024, 1010, 5776, 2001, 2872, 2006, 1996, 25022, 11890, 2819, 28472, 19355, 2604, 1012, 7861, 2721, 2018, 2042, 4162, 3155, 3938, 2781, 2077, 1012, 1037, 2051, 1011, 2041, 2001, 2949, 2938, 2483, 7011, 16761, 6588, 2566, 8778, 1012, 1996, 2181, 2001, 17463, 5669, 2007, 8247, 10672, 1012, 1996, 18921, 29334, 2001, 15517, 2007, 25403, 18856, 25167, 1998, 2001, 4487, 11393, 10985, 2185, 2013, 1996, 21887, 1998, 1996, 1043, 5802, 2015, 19085, 2007, 14969, 4487, 11393, 7542, 1012, 1037, 9587, 6914, 18856, 16613, 2001, 4162, 2000, 1996, 8292, 2099, 5737, 2595, 1012, 1996, 9987, 18921, 29334, 2001, 4654, 18380, 2094, 2007, 1996, 21065, 2884, 1012, 1996, 18856, 16613, 2001, 371

In [20]:
!pip install -U transformers datasets evaluate

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.4/81.4 KB 4.4 MB/s eta 0:00:00


In [21]:
import numpy as np
toy_labels = np.array([1]*5 + [0]*5)
print(toy_labels)

[1 1 1 1 1 0 0 0 0 0]


In [24]:
np.random.seed(0)
toy_logits = np.random.randn(10, 2)
print(toy_logits)

[[ 1.76405235  0.40015721]
 [ 0.97873798  2.2408932 ]
 [ 1.86755799 -0.97727788]
 [ 0.95008842 -0.15135721]
 [-0.10321885  0.4105985 ]
 [ 0.14404357  1.45427351]
 [ 0.76103773  0.12167502]
 [ 0.44386323  0.33367433]
 [ 1.49407907 -0.20515826]
 [ 0.3130677  -0.85409574]]


In [25]:
toy_preds = np.argmax(toy_logits, axis = -1)
print(toy_preds)

[0 1 0 0 1 1 0 0 0 0]


In [26]:
toy_result = pd.DataFrame(zip(toy_labels, toy_preds), columns = ('True', 'Pred'))
toy_result

True  Pred
0     1     0
1     1     1
2     1     0
3     1     0
4     1     1
5     0     1
6     0     0
7     0     0
8     0     0
9     0     0

In [27]:
def evaluate(pair):
  true, pred = pair
  head = 'T' if true == pred else 'F'
  tail = 'P' if pred else 'N'
  return head + tail

toy_result['Class'] = toy_result[['True', 'Pred']].apply(evaluate, axis = 1)
toy_result

True  Pred Class
0     1     0    FN
1     1     1    TP
2     1     0    FN
3     1     0    FN
4     1     1    TP
5     0     1    FP
6     0     0    TN
7     0     0    TN
8     0     0    TN
9     0     0    TN

In [28]:
counts = toy_result['Class'].value_counts()
print(counts)

TN    4
FN    3
TP    2
FP    1
Name: Class, dtype: int64


In [29]:
from evaluate import load

#accuracy = 6/10 = 0.6
#toy_accuracy = accuracy 계산하는 코드 작성

print(toy_accuracy)
print(load('accuracy').compute(predictions = toy_preds, references = toy_labels))

NameError: ignored